
module Utils::Constants
  # Resource ID constants
  USER_ID_LENGTH = 36
  USER_ID_STRING_LENGTH = 49 # USER_ID_LENGTH + 1 + String::HEADER_SIZE

  MUSIC_ID_LENGTH = 22
  MUSIC_ID_STRING_LENGTH = 35 # MUSIC_ID_LENGTH + 1 + String::HEADER_SIZE

  PLAYLIST_ID_LENGTH = 22
  PLAYLIST_ID_STRING_LENGTH = 35 # PLAYLIST_ID_LENGTH + 1 + String::HEADER_SIZE

  # Auth middleware constants
  EXPECTED_AUTH_HEADER_SIZE = 109 # 7 + ACCESS_TOKEN_SIZE
  BLACK_LIST_TOKEN_ID_STRING_LENGTH = 126 # 11 + ACCESS_TOKEN_SIZE + 1 + String::HEADER_SIZE

  # Token constants
  ACCESS_CLAIMS_SIZE = 44 # USER_ID_LENGTH + 8
  REFRESH_CLAIMS_SIZE = 84 # USER_ID_LENGTH + TOKEN_FAMILY_ID_LENGTH + 4 + 8

  TOKEN_FAMILY_ID_LENGTH = 36
  TOKEN_FAMILY_ID_STRING_LENGTH = 49 # TOKEN_FAMILY_ID_LENGTH + 1 + String::HEADER_SIZE

  # User validator constants
  MAX_EMAIL_LENGTH = 60

  MIN_PASSWORD_LENGTH = 8
  MAX_PASSWORD_LENGTH = 71

  MAX_FIRST_NAME_LENGTH = 50
  MAX_LAST_NAME_LENGTH = 50

  # Music validator constants
  MAX_MUSIC_FILE_SIZE = 25_000_000 # 25,000,000 bytes, or 25MB
  MAX_COVER_ART_FILE_SIZE = 8_000_000 # 8,000,000 bytes, or 8MB

  MAX_TITLE_LENGTH = 150
  MAX_ARTIST_LENGTH = 100

  MAX_TITLE_STRING_LENGTH = 163 # MAX_TITLE_LENGTH + 1 + String::HEADER_SIZE
  MAX_ARTIST_STRING_LENGTH = 113 # MAX_ARTIST_LENGTH + 1 + String::HEADER_SIZE

  PNG_HEADER = UInt8.static_array(137, 80, 78, 71, 13, 10, 26, 10)
  PNG_IMAGE_END = UInt8.static_array(73, 69, 78, 68, 174, 66, 96, 130)

  JPEG_HEADER = UInt8.static_array(255, 216)
  JPEG_IMAGE_END = UInt8.static_array(255, 217)

  OGG_HEADER = UInt8.static_array(79, 103, 103, 83)

  MP3_HEADER = UInt8.static_array(73, 68, 51, 3)

  UPDATE_MUSIC_WORK_BUFFER_SIZE = 254

  # Music repository constants
  MUSIC_FILE_ID_STRING_LENGTH = 72 # USER_ID_LENGTH + 1 + MUSIC_ID_LENGTH + 1 + String::HEADER_SIZE
  COVER_ART_ID_STRING_LENGTH = 82  # USER_ID_LENGTH + 1 + MUSIC_ID_LENGTH + 10 + 1 + String::HEADER_SIZE

  DEFAULT_S3_HEADER = Hash(String, String).new

  # Music controller constants
  MUSIC_ENDPOINT_PREFIX_LENGTH = 19 # "/api/v1/users/music".size

  ADD_MUSIC_REQUEST_BUFFER_SIZE = 276 # MAX_TITLE_STRING_LENGTH + MAX_ARTIST_STRING_LENGTH
  UPDATE_MUSIC_REQUEST_BUFFER_SIZE = 276 # MAX_TITLE_STRING_LENGTH + MAX_ARTIST_STRING_LENGTH

  GET_MUSIC_FILE_PATH_SIZE = 23 # 1 + MUSIC_ID_LENGTH
  GET_MUSIC_COVER_ART_PATH_SIZE = 33 # 1 + MUSIC_ID_LENGTH + "/cover-art".size
  SET_MUSIC_COVER_ART_PATH_SIZE = 33 # 1 + MUSIC_ID_LENGTH + "/cover-art".size
  UPDATE_MUSIC_PATH_SIZE = 23 # 1 + MUSIC_ID_LENGTH
  DELETE_MUSIC_PATH_SIZE = 23 # 1 + MUSIC_ID_LENGTH

  # Playlist validator constants
  MAX_PLAYLIST_NAME_LENGTH = 80

  # Playlist controller constants
  PLAYLIST_ENDPOINT_PREFIX_LENGTH = 23 # "/api/v1/users/playlists".size

  ADD_PLAYLIST_REQUEST_BUFFER_SIZE = 93 # MAX_PLAYLIST_NAME_LENGTH + 1 + String::HEADER_SIZE
  ADD_PLAYLIST_MUSIC_REQUEST_BUFFER_SIZE = 35 # MUSIC_ID_LENGTH + 1 + String::HEADER_SIZE
  UPDATE_PLAYLIST_REQUEST_BUFFER_SIZE = 93 # MAX_PLAYLIST_NAME_LENGTH + 1 + String::HEADER_SIZE

  ADD_PLAYLIST_MUSIC_PATH_SIZE = 29 # 1 + PLAYLIST_ID_LENGTH + "/music".size
  GET_PLAYLIST_PATH_SIZE = 23 # 1 + PLAYLIST_ID_LENGTH
  UPDATE_PLAYLIST_PATH_SIZE = 23 # 1 + PLAYLIST_ID_LENGTH
  UPDATE_PLAYLIST_MUSIC_PATH_SIZE = 52 # 1 + PLAYLIST_ID_LENGTH + "/music/".size + MUSIC_ID_LENGTH
  DELETE_PLAYLIST_PATH_SIZE = 23 # 1 + PLAYLIST_ID_LENGTH
  DELETE_PLAYLIST_MUSIC_PATH_SIZE = 52 # 1 + PLAYLIST_ID_LENGTH + "/music/".size + MUSIC_ID_LENGTH

  UPDATE_PLAYLIST_MUSIC_OFFSET = 23 # 1 + PLAYLIST_ID_LENGTH
  UPDATE_PLAYLIST_MUSIC_MUSIC_ID_OFFSET = 30 # 1 + PLAYLIST_ID_LENGTH + "/music/".size
  DELETE_PLAYLIST_MUSIC_OFFSET = 23 # 1 + PLAYLIST_ID_LENGTH
  DELETE_PLAYLIST_MUSIC_MUSIC_ID_OFFSET = 30 # 1 + PLAYLIST_ID_LENGTH + "/music/".size
end
