# HTTP_METHOD ENDPOINT CAPACITY REFILL_AMOUNT REFILL_INTERVAL
POST /api/v1/users/login 12 6 1800
GET /api/v1/users/music/{music_id} 80 40 1800
GET /api/v1/users/music/{music_id}/cover-art 80 40 1800
PUT /api/v1/users/music/{music_id}/cover-art 80 40 1800
